### ISSUE TITLE
Para el `Stamp` aceptar JSON fortmat ( dict() )

### ISSUE THREAD

**Issue by Brunux** [lunasoft/sw-sdk-python#3]
```python
...
payload = {'emisor': { 'rfc': 'XXXX', 'cp': 'XXXX'} ... }
objStamp = Stamp("http://services.test.sw.com.mx", token)
objResponseStamp = objStamp.StampV4(payload))
```

**Comment by JuanGamezSW** [comment]
El método de issue_json soporta ahora el uso de un dict. Solo asegúrate de que vaya con el formato que acepta el servicio. Documentación [aquí](https://developers.sw.com.mx/knowledge-base/emision-timbrado-json-cfdi-3-3/)
